# ---------------- #
#   Main Configs   #
# ---------------- #
# 网站默认根地址
baseurl:  
url:  https://super456.github.io
date_format: "ordinal"
# 网站标题
title: "猿来缘往"
# 个性签名
subtitle: "在岁月的长河里寻找一种度过时光的乐趣"
# 在博客订阅显示
description: "世武的个人博客记录"
# keywords: 猿来缘往, Du Shiwu, 杜世武
# 网站图标
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
# 显示在我的开源仓库数量设置
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
# 底部页脚展示名字
author: 世武呦
# organization: url
# organization_url: url
github_username: super456
location: Guangzhou, China
email: 1061996681@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
# 页面顶部导航栏
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
# 代码高亮设置
highlighter: rouge
# 分页显示数量设置
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository:  super456/super456.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie, gitment
comments_provider: gitment
# https://disqus.com
disqus:
   username: super456
# https://gentie.163.com   网易云跟帖
# netease_gentie:
#     productKey: 560ed243b708465d82d5a0a5f3b83da1
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: super456
    repo: blog-comments
    oauth:
        client_id: ef96c2da698852e79799
        client_secret: 34be242b665379a6c85da40d53c51ef4deab076f

# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
# 谷歌分析工具
google:
analytics_id: UA-103090780-1

#我自己加的
gist:
  noscript: false
gems: ['jekyll-github-metadata']
github: [metadata]
