/** AI 工具 */
export default {
  title: 'AI 工具',
  items: [
    {
      title: 'Latent Box',
      desc: 'AI、创意和艺术领域的精选合集，来自 Latent Cat。',
      icon: 'https://latentbox.com/favicon.ico',
      link: 'https://latentbox.com/zh',
    },
    {
      title: 'AI工具导航 | 国内外AI工具集导航大全',
      desc: 'AI导航汇集了数百种国内外优秀的AI工具，包括AI写作工具、AI图像生成和背景处理、AI视频制作、AI音频转录、AI辅助编程、AI音乐生成、AI绘画设计、AI对话聊天等领域的顶尖工具，同时还提供常用的AI学习开发网站、框架和模型库，以助你轻松融入人工智能的世界，高效自动化完成任务！',
      icon: 'https://nancheng.fun/wp-content/uploads/2024/02/favicon.png',
      link: 'https://ai.nancheng.fun/',
    },
    {
      title: 'WaytoAGI-通往AGI之路，最好的 AI 知识库和工具站',
      desc: '最大最全面的 AI 知识库，汇聚上千个人工智能网站和工具，汇集最新的 AI 工具、GPT 应用和行业资讯。无论您是AI爱好者、研究者还是开发者，WaytoAGI助力您在通往AGI的旅途中开启智能创新的未来。',
      icon: 'https://www.waytoagi.com/favicon.ico',
      link: 'https://www.waytoagi.com/',
    },
    {
      icon: '/icons/chatgpt.png',
      title: 'ChatGPT',
      desc: 'AI 聊天对话',
      link: 'https://chat.openai.com/chat',
    },
    {
      title: 'Kimi.ai - 帮你看更大的世界',
      desc: 'Kimi 是一个有着超大“内存”的智能助手，可以一口气读完二十万字的小说，还会上网冲浪，快来跟他聊聊吧 | Kimi.ai - Moonshot AI 出品的智能助手',
      icon: 'https://statics.moonshot.cn/kimi-chat/favicon.ico',
      link: 'https://kimi.moonshot.cn/',
    },
    {
      title: '扣子 - AI 智能体开发平台',
      desc: '扣子是新一代 AI 大模型智能体开发平台。整合了插件、长短期记忆、工作流、卡片等丰富能力，扣子能帮你低门槛、快速搭建个性化或具备商业价值的智能体，并发布到豆包、飞书等各个平台。',
      icon: 'https://lf-coze-web-cdn.coze.cn/obj/coze-web-cn/obric/coze/favicon.1970.png',
      link: 'https://www.coze.cn/',
    },
    {
      icon: 'https://metaso.cn/favicon.ico',
      title: '秘塔 AI 搜索',
      desc: '知识类内容检查，没有广告直达结果，分析深入',
      link: 'https://metaso.cn/',
    },
    {
      icon: 'https://static.tiangong.cn/mainsite/logo.ico',
      title: '天工 AI',
      desc: '「天工」是国内首个对标 ChatGPT 的双千亿级大语言模型，也是一个对话式AI助手。「天工」通过自然语言与用户进行问答交互，AI 生成能力可满足文案创作、知识问答、逻辑推演、数理推算、代码编程等多元化需求。支持1万字以上文本对话，实现20轮次以上用户交互，在学习、职场、生活等多类问答场景中都能实现较高的输出水平。',
      link: 'https://beta.tiangong.cn/',
    },
    {
      icon: 'https://nlp-eb.cdn.bcebos.com/logo/favicon.ico',
      title: '文心一言',
      desc: '既能写文案、读文档，又能脑洞大开、答疑解惑，还能倾听你的故事、感受你的心声。快来和我对话吧！',
      link: 'https://yiyan.baidu.com/welcome',
    },
    {
      icon: 'https://www.notion.so/images/logo-ios.png',
      title: 'Notion AI',
      desc: 'AI 输入笔记',
      link: 'https://www.notion.so',
    },
    {
      icon: 'https://www.midjourney.com/apple-touch-icon.png',
      title: 'Midjourney',
      desc: 'AI 绘画',
      link: 'https://www.midjourney.com',
    },
    {
      icon: 'https://stablediffusionweb.com/images/logo.png',
      title: 'Stable Diffusion Online',
      desc: 'AI 绘画',
      link: 'https://stablediffusionweb.com/',
    },
    {
      icon: 'https://global-uploads.webflow.com/59deb588800ae30001ec19c9/5d4891e0e260e3c1bc37b100_beautiful%20ai%20favicon%20%20blue%20square.png',
      title: 'Beautiful.ai',
      desc: 'AI 生成PPT',
      link: 'https://www.beautiful.ai',
    },
    {
      icon: 'https://www.suno.ai/favicon.svg',
      title: 'Suno AI',
      desc: 'AI 生成音乐',
      link: 'https://www.suno.ai/',
    },
    {
      icon: 'https://acd-assets.alicdn.com/acd_work/tongyi-portal/favicon.png',
      title: '通义系列官网',
      desc: '通义官网，致力于实现类人智慧的通用智能，强烈推荐：通义灵码、通义听悟、通义前文',
      link: 'https://tongyi.aliyun.com/',
    },
    {
      icon: 'https://comate.baidu.com/images/favicon.ico',
      title: 'Baidu Comate',
      desc: '由百度基于文心大模型研发的编程辅助工具，可提供自动代码生成、单元测试生成、注释生成以及智能问答等功能。支持上百种编程语言，旨在帮助开发者大幅提升编码效率。使用Comate，让编程更加高效和便捷。',
      link: 'https://comate.baidu.com/',
    },
    {
      title: 'AI帮个忙 | 多功能AI小帮手',
      desc: 'AI帮个忙是打工人的多功能小帮手，有多个AI写作和图片工具，可以用AI生成小红书文案，文章，PPT大纲等，支持改写，润色,续写,扩写',
      icon: 'https://aibang.run/favicon-32x32.png',
      link: 'https://aibang.run/',
    },
    {
      title: '一起用AI | AI副业搞钱套路集合站点',
      desc: '一起用AI 智能化搞副业赚钱 | AI副业搞钱套路集合站点',
      icon: 'https://17yongai.com/wp-content/uploads/2023/02/logo.png',
      link: 'https://17yongai.com/',
    },
    {
      title: '秘塔写作猫',
      desc: '写作猫是新一代交互式中英文写作辅助平台，集智能文本纠错、改写润色、自动续写、智能配图为一体。',
      icon: 'https://metaso.cn/favicon.ico',
      link: 'https://xiezuocat.com/',
    },
    {
      title: 'AgentGPT',
      desc: 'Assemble, configure, and deploy autonomous AI Agents in your browser.',
      icon: 'https://agentgpt.reworkd.ai/favicon.svg',
      link: 'https://agentgpt.reworkd.ai/zh',
    },
    {
      title: '鱼聪明AI，做您强大的AI助手',
      desc: '机器人聊天,人工智能对话,ChatGPT,OpenAI,编程助手,智能助手,AI绘画,AI模型,AI工具',
      icon: 'https://www.yucongming.com/favicon.ico',
      link: 'https://www.yucongming.com/',
    },
  ],
}
