/** 有趣的工具 */
export default {
  title: '有趣工具',
  items: [
    {
      title: 'Koishi',
      desc: '创建跨平台、可扩展、高性能的机器人',
      icon: 'https://koishi.chat/logo.png',
      link: 'https://koishi.chat/zh-CN/',
    },
    {
      title: 'Quick Reference',
      desc: '为开发人员分享快速参考备忘清单【速查表】',
      link: 'https://wangchujiang.com/reference/index.html',
      icon: '/icons/quick-reference.svg',
    },
    {
      icon: 'https://qwerty.fe-mm.com/apple-touch-icon.png',
      title: 'Qwerty Learner',
      desc: '为键盘工作者设计的单词记忆与英语肌肉记忆锻炼软件',
      link: 'https://qwerty.fe-mm.com',
    },
    {
      icon: 'https://transform.tools/static/favicon.png',
      title: 'Transform',
      desc: '一个支持多语言的在线转换器',
      link: 'https://npm.devtool.tech/',
    },
    {
      title: 'Excalidraw Editor',
      desc: '手绘风格流程图',
      icon: 'https://avatars.githubusercontent.com/u/59452120?s=48&v=4',
      link: 'https://excalidraw.com/',
    },
    {
      title: 'tldraw',
      desc: 'A free and instant collaborative diagramming tool.',
      icon: 'https://www.tldraw.com/favicon.svg',
      link: 'https://www.tldraw.com/',
    },
    {
      title: 'draw.io',
      desc: 'Security-first diagramming for teams',
      icon: 'https://www.drawio.com/favicon.ico',
      link: 'https://www.drawio.com/',
    },
    {
      title: '使用简单的文字描述画UML图的开源工具。',
      desc: '轻松从简单的文字说明创建UML图。也有许多种可用的图表。它也可以以PNG，LaTeX，EPS，SVG格式图像导出。',
      icon: 'https://plantuml.com/favicon.ico',
      link: 'https://plantuml.com/zh/#google_vignette',
    },
    {
      icon: 'https://www.processon.com/public_login/favicon.983368c6.ico',
      title: 'ProcessOn',
      desc: '免费在线流程图思维导图',
      link: 'https://www.processon.com/',
    },
    {
      icon: 'https://shields.io/img/logo.png',
      title: 'Shields.io',
      desc: '制作简洁、一致、易读的徽章',
      link: 'https://shields.io/',
    },
    {
      icon: 'https://carbon.now.sh/favicon.ico',
      title: 'Carbon',
      desc: '代码图片生成',
      link: 'https://carbon.now.sh/',
    },
    {
      icon: 'https://www.codecopy.cn/favicon.ico',
      title: '代码小抄',
      desc: '简单易用的代码分享工具',
      link: 'https://www.codecopy.cn/',
    },
    {
      title: 'publint',
      desc: 'Lint if a package is published right',
      icon: 'https://publint.dev/favicon.ico',
      link: 'https://publint.dev/',
    },
    {
      title: 'npm-start: download statistics for NPM packages',
      desc: 'npm-stat can generate download charts for any package on npm.',
      icon: 'https://npm-stat.com/favicon.ico',
      link: 'https://npm-stat.com/',
    },
    {
      title: 'pkg-size',
      desc: 'Find the true size of an npm package',
      icon: 'https://pkg-size.dev/favicon.svg',
      link: 'https://pkg-size.dev/',
    },
    {
      title: 'GZIP compression Test',
      desc: 'Test if Gzip or Brotli is working on your website. Brotli is a better, and newer compression method compared to Gzip.',
      icon: 'https://www.giftofspeed.com/assets/images/favicon.png',
      link: 'https://www.giftofspeed.com/gzip-test/',
    },
    {
      title: 'CODELF-在线取名',
      desc: 'Codelf,变量命名,函数命名,方法命名,变量命名神器,GitHub 分组,Organize GitHub stars,naming things,naming convention,programming naming',
      icon: 'https://unbug.github.io/codelf/images/codelf_logo.f4ae25bd.png',
      link: 'https://unbug.github.io/codelf/',
    },
    {
      title: 'Timeline editor',
      desc: 'Free online timeline editor. A lot of events, parameters. Upload images, video youtube etc.',
      icon: 'https://time.graphics/favicon.ico?v=7kbn8X5BAk',
      link: 'https://time.graphics/editor',
    },
    {
      title: 'Heptabase',
      desc: 'A note-taking tool for visual learning.',
      icon: 'https://heptabase.com/assets/images/favicon.png',
      link: 'https://heptabase.com/',
    },
    {
      title: 'Inpaint-web在线工具——永久免费一键去除照片中不想要的对象 & 修复瑕疵',
      desc: '只需一点击，轻松去除照片中的不想要的对象。Inpaint提供了令人难以置信的照片去除和修复功能。',
      link: 'https://inpaintweb.lxfater.com/',
    },
    {
      title: '易采集EasySpider：无代码可视化爬虫/浏览器自动化测试软件',
      desc: '易采集EasySpider，又称Easy Spider，是一个可视化爬虫/浏览器自动化测试软件，可以使用图形化界面，无代码可视化的设计和执行爬虫/浏览器自动化测试任务。只需要在网页上选择自己想要爬的内容并根据提示框操作即可完成爬虫/浏览器自动化测试任务的设计和执行。同时软件还可以单独以命令行的方式进行执行，从而可以很方便的嵌入到其他系统中。',
      icon: 'https://www.easyspider.net/favicon.ico',
      link: 'https://www.easyspider.net/',
    },
  ],
}
