/** Vue 技术栈生态 */
export default {
  title: 'Vue',
  items: [
    {
      icon: 'https://cn.vuejs.org/logo.svg',
      title: 'Vue 3',
      desc: '渐进式 JavaScript 框架',
      link: 'https://cn.vuejs.org',
    },
    {
      icon: 'https://cn.vuejs.org/logo.svg',
      title: 'Vue 2',
      desc: '渐进式 JavaScript 框架',
      link: 'https://v2.cn.vuejs.org',
    },
    {
      icon: 'https://cn.vuejs.org/logo.svg',
      title: 'Vue Router',
      desc: 'Vue.js 的官方路由，为 Vue.js 提供富有表现力、可配置的、方便的路由',
      link: 'https://router.vuejs.org/zh',
    },
    {
      icon: 'https://pinia.vuejs.org/logo.svg',
      title: 'Pinia',
      desc: '符合直觉的 Vue.js 状态管理库',
      link: 'https://pinia.vuejs.org/zh',
    },
    {
      title: 'Vuex',
      desc: '一个专为 Vue.js 应用程序开发的状态管理模式 + 库。它采用集中式存储管理应用的所有组件的状态，并以相应的规则保证状态以一种可预测的方式发生变化',
      icon: 'https://cn.vuejs.org/logo.svg',
      link: 'https://vuex.vuejs.org/zh/',
    },
    {
      icon: 'https://nuxt.com/icon.png',
      title: 'Nuxt.js',
      desc: '一个基于 Vue.js 的通用应用框架',
      link: 'https://nuxt.com',
    },
    {
      icon: 'https://vueuse.org/favicon.svg',
      title: 'VueUse',
      desc: 'Vue Composition API 的常用工具集',
      link: 'https://vueuse.org',
    },
    {
      title: 'Vue Macros',
      desc: '探索更多宏和语法糖到 Vue 中',
      icon: 'https://vue-macros.dev/favicon.svg',
      link: 'https://vue-macros.dev/zh-CN/',
    },
    {
      title: 'Vue.js 挑战',
      desc: '一个 Vue.js 在线挑战平台',
      icon: 'https://cn-vuejs-challenges.netlify.app/logo.png',
      link: 'https://cn-vuejs-challenges.netlify.app/',
    },
    {
      icon: 'https://element-plus.org/images/element-plus-logo-small.svg',
      title: 'Element Plus',
      desc: '基于 Vue 3，面向设计师和开发者的组件库',
      link: 'https://element-plus.org',
    },
    {
      icon: 'https://www.antdv.com/assets/logo.1ef800a8.svg',
      title: 'Ant Design Vue',
      desc: 'Ant Design 的 Vue 实现，开发和服务于企业级后台产品',
      link: 'https://antdv.com',
    },
    {
      title: 'Arco Design Vue',
      desc: '基于 Arco Design 的 Vue UI 组件库，60多个开箱即用的高质量组件, 可以覆盖绝大部份的业务场景',
      icon: 'https://unpkg.byted-static.com/latest/byted/arco-config/assets/favicon.ico',
      link: 'https://arco.design/vue/docs/start',
    },
    {
      icon: 'https://fastly.jsdelivr.net/npm/@vant/assets/logo.png',
      title: 'Vant',
      desc: '轻量、可定制的移动端 Vue 组件库',
      link: 'https://vant-ui.github.io/vant',
    },
    {
      icon: 'https://webapp.didistatic.com/static/webapp/shield/Cube-UI_logo.ico',
      title: 'Cube UI',
      desc: '基于 Vue.js 实现的精致移动端组件库',
      link: 'https://didi.github.io/cube-ui',
    },
    {
      icon: 'https://img14.360buyimg.com/imagetools/jfs/t1/167902/2/8762/791358/603742d7E9b4275e3/e09d8f9a8bf4c0ef.png',
      title: 'NutUI',
      desc: '京东风格的轻量级移动端组件库',
      link: 'https://nutui.jd.com',
    },
    {
      icon: 'https://varlet.gitee.io/varlet-ui/varlet_icon.png',
      title: 'Varlet',
      desc: '基于 Vue3 开发的 Material 风格移动端组件库',
      link: 'https://varlet.gitee.io/varlet-ui/#/zh-CN/index',
    },
    {
      icon: 'https://www.naiveui.com/assets/naivelogo-XQ1U1Js8.svg',
      title: 'Naïve UI',
      desc: '一个 Vue 3 组件库，比较完整，主题可调，使用 TypeScript，快有点意思',
      link: 'https://www.naiveui.com/zh-CN/os-theme',
    },
    {
      icon: 'https://vue-devui.github.io/assets/logo.svg',
      title: 'Vue DevUI',
      desc: '一个基于 DevUI Design 的 Vue3 组件库',
      link: 'https://vue-devui.github.io/',
    },
    {
      icon: 'https://fantastic-admin.github.io/logo.png',
      title: 'Fantastic-admin',
      desc: '一款开箱即用的 Vue 中后台管理系统框架，支持多款 UI 组件库，兼容PC、移动端。vue-admin, vue-element-admin, vue后台, 后台系统, 后台框架, 管理后台, 管理系统',
      link: 'https://fantastic-admin.github.io/',
    },
    {
      title: 'iView / View Design 一套企业级 UI 组件库和前端解决方案',
      desc: '基于 Vue.js 3 的企业级 UI 组件库和中后台系统解决方案，为数万开发者服务',
      icon: 'https://file.iviewui.com/view-design-logo.png',
      link: 'https://www.iviewui.com/',
    },
  ],
}
